In [1]:
import numpy as np
import neuroscope as ns
from bs4 import BeautifulSoup

In [2]:
with open('D:/BuzsakiData/SenzaiY/YutaMouse41/YutaMouse41-150903/YutaMouse41-150903.xml', 'r') as xml_file:
    contents = xml_file.read()
    soup = BeautifulSoup(contents, 'xml')

In [3]:
soup

<?xml version="1.0" encoding="utf-8"?>
<parameters creator="ndManager-" version="1.0">
<generalInfo>
<date>2015-08-31</date>
<experimenters>yuta</experimenters>
<description/>
<notes/>
</generalInfo>
<acquisitionSystem>
<nBits>16</nBits>
<nChannels>80</nChannels>
<samplingRate>20000</samplingRate>
<voltageRange>20</voltageRange>
<amplification>1000</amplification>
<offset>0</offset>
</acquisitionSystem>
<fieldPotentials>
<lfpSamplingRate>1250</lfpSamplingRate>
</fieldPotentials>
<anatomicalDescription>
<channelGroups>
<group>
<channel skip="0">33</channel>
<channel skip="0">38</channel>
<channel skip="0">32</channel>
<channel skip="0">39</channel>
<channel skip="0">35</channel>
<channel skip="0">36</channel>
<channel skip="0">34</channel>
<channel skip="0">37</channel>
</group>
<group>
<channel skip="0">41</channel>
<channel skip="0">46</channel>
<channel skip="0">40</channel>
<channel skip="0">47</channel>
<channel skip="0">43</channel>
<channel skip="0">44</channel>
<channel skip="0"

In [4]:
nChannels = int(soup.nChannels.string)
nSamples = int(soup.nSamples.string)
bitType = int(soup.nBits.string)

In [5]:
print(nChannels)
print(nSamples)
print(bitType)

80
32
16


In [6]:
filepath = 'D:/BuzsakiData/SenzaiY/YutaMouse41/YutaMouse41-150903/YutaMouse41-150903-01.dat';
RawData = np.memmap(filepath,shape=(nSamples,nChannels),dtype='int'+str(bitType))

In [7]:
RawData[0:2,:]

memmap([[2672, 2696, 2528, 2580, 2664, 2464, 2640, 2628, 2940, 2740,
         2628, 2932, 2584, 2672, 3464, 2928, 2036, 2136, 1776, 2252,
         1940, 1904, 2052, 2488, 2044, 2004, 2408, 2444, 2384, 2432,
         2396, 2132, 2076, 2148, 1784, 2268, 1916, 2064, 1800, 1980,
         1700, 2140, 1884, 1780, 1716, 1776, 1656, 1972, 2744, 3000,
         2864, 2976, 2412, 3052, 3100, 3172, 2888, 3184, 2780, 3328,
         2856, 2936, 3060, 3024, 1360,  904, 1376, 1356, 1464, 1312,
         1100, 1464, 1276, 1408, 1368, 1156, 1652, 1452, 1888, 1240],
        [2696, 2676, 2492, 2616, 2672, 2540, 2656, 2612, 2936, 2784,
         2636, 2968, 2572, 2704, 3504, 2940, 2120, 2128, 1780, 2244,
         1992, 1932, 2064, 2448, 2064, 2024, 2436, 2436, 2380, 2432,
         2368, 2156, 2068, 2160, 1740, 2268, 1924, 2124, 1828, 1996,
         1700, 2128, 1856, 1796, 1752, 1796, 1660, 1988, 2772, 3004,
         2848, 2956, 2420, 3112, 3076, 3240, 2868, 3116, 2728, 3344,
         2872, 2912, 3036, 3012, 

In [8]:
RawData[:,0:4]

memmap([[2672, 2696, 2528, 2580],
        [2696, 2676, 2492, 2616],
        [2684, 2688, 2552, 2648],
        [2652, 2676, 2524, 2664],
        [2608, 2656, 2504, 2600],
        [2612, 2608, 2464, 2564],
        [2624, 2612, 2472, 2608],
        [2580, 2628, 2440, 2608],
        [2544, 2588, 2436, 2608],
        [2580, 2564, 2456, 2572],
        [2560, 2600, 2520, 2616],
        [2592, 2600, 2484, 2632],
        [2596, 2612, 2496, 2664],
        [2524, 2620, 2496, 2612],
        [2532, 2628, 2404, 2572],
        [2544, 2644, 2420, 2556],
        [2552, 2596, 2420, 2596],
        [2564, 2636, 2456, 2588],
        [2596, 2624, 2444, 2564],
        [2640, 2688, 2504, 2608],
        [2644, 2664, 2524, 2604],
        [2672, 2648, 2556, 2632],
        [2652, 2656, 2524, 2620],
        [2640, 2656, 2560, 2648],
        [2644, 2676, 2516, 2660],
        [2656, 2664, 2512, 2636],
        [2708, 2636, 2552, 2692],
        [2728, 2664, 2612, 2684],
        [2704, 2688, 2576, 2692],
        [2696,

In [9]:
RawDataNewShape = np.memmap(filepath,shape=(nChannels,nSamples),dtype='int'+str(bitType)).transpose()

In [10]:
RawDataNewShape[:,0]

memmap([2672, 2696, 2528, 2580, 2664, 2464, 2640, 2628, 2940, 2740, 2628,
        2932, 2584, 2672, 3464, 2928, 2036, 2136, 1776, 2252, 1940, 1904,
        2052, 2488, 2044, 2004, 2408, 2444, 2384, 2432, 2396, 2132],
       dtype=int16)

In [11]:
shank_channels = [[int(channel.string)
                       for channel in group.find_all('channel')]
                      for group in soup.spikeDetection.channelGroups.find_all('group')]

In [12]:
shank_channels

[[33, 38, 32, 39, 35, 36, 34, 37],
 [41, 46, 40, 47, 43, 44, 42, 45],
 [16, 25, 17, 24, 18, 22, 20, 21],
 [26, 19, 28, 23, 29, 27, 30, 31],
 [13, 4, 9, 2, 5, 3, 1, 0],
 [7, 14, 6, 15, 8, 12, 11, 10],
 [48, 55, 49, 54, 50, 53, 51, 52],
 [56, 63, 57, 62, 58, 61, 59, 60]]

In [13]:
all_shank_channels = np.concatenate(shank_channels[:8])

In [14]:
all_shank_channels

array([33, 38, 32, 39, 35, 36, 34, 37, 41, 46, 40, 47, 43, 44, 42, 45, 16,
       25, 17, 24, 18, 22, 20, 21, 26, 19, 28, 23, 29, 27, 30, 31, 13,  4,
        9,  2,  5,  3,  1,  0,  7, 14,  6, 15,  8, 12, 11, 10, 48, 55, 49,
       54, 50, 53, 51, 52, 56, 63, 57, 62, 58, 61, 59, 60])

In [30]:
data = np.arange(12, dtype='float32').reshape(12,1)
print(data)

from tempfile import mkdtemp
import os.path as path
filename = path.join(mkdtemp(), 'newfile.dat')

fp = np.memmap(filename, dtype='float32', mode='w+', shape=(12,1))
fp[:] = data
fp.filename == path.abspath(filename)
del fp
newfp = np.memmap(filename, dtype='float32', mode='r', shape=(3,4))
print(newfp)

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
